// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice =
  ContentSlice | ImageSlice | VideoSlice | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  ContentSlice | VideoSlice | ImageSlice | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SettingsDocumentDataSlicesSlice = never;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>; /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: settings.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: settings.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = HomeDocument | PageDocument | SettingsDocument;

/**
 * Item in *Content → Text Only → Primary → Calls to action*
 */
export interface ContentSliceDefaultPrimaryCtasItem {
  /**
   * Label field in *Content → Text Only → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button label
   * - **API ID Path**: content.default.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Content → Text Only → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional call to action
   * - **API ID Path**: content.default.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Item in *Content → Centered Text → Primary → Calls to action*
 */
export interface ContentSliceCenteredTextPrimaryCtasItem {
  /**
   * Label field in *Content → Centered Text → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button label
   * - **API ID Path**: content.centeredText.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Content → Centered Text → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional call to action
   * - **API ID Path**: content.centeredText.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Item in *Content → Image Right → Primary → Calls to action*
 */
export interface ContentSliceImageRightPrimaryCtasItem {
  /**
   * Label field in *Content → Image Right → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button label
   * - **API ID Path**: content.imageRight.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Content → Image Right → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional call to action
   * - **API ID Path**: content.imageRight.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Item in *Content → Image Left → Primary → Calls to action*
 */
export interface ContentSliceImageLeftPrimaryCtasItem {
  /**
   * Label field in *Content → Image Left → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button label
   * - **API ID Path**: content.imageLeft.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Content → Image Left → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional call to action
   * - **API ID Path**: content.imageLeft.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Primary content in *Content → Text Only → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * Eyebrow field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional short label above the heading
   * - **API ID Path**: content.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: content.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Editorial content
   * - **API ID Path**: content.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Calls to action field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<ContentSliceDefaultPrimaryCtasItem>>;

  /**
   * Section spacing field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose space above and below this section
   * - **Default Value**: standard
   * - **API ID Path**: content.default.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the maximum content width
   * - **Default Value**: standard
   * - **API ID Path**: content.default.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;
}

/**
 * Text Only variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Content → Centered Text → Primary*
 */
export interface ContentSliceCenteredTextPrimary {
  /**
   * Eyebrow field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional short label above the heading
   * - **API ID Path**: content.centeredText.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: content.centeredText.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Editorial content
   * - **API ID Path**: content.centeredText.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Calls to action field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.centeredText.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<ContentSliceCenteredTextPrimaryCtasItem>>;

  /**
   * Section spacing field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose space above and below this section
   * - **Default Value**: standard
   * - **API ID Path**: content.centeredText.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the maximum content width
   * - **Default Value**: standard
   * - **API ID Path**: content.centeredText.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;
}

/**
 * Centered Text variation for Content Slice
 *
 * - **API ID**: `centeredText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceCenteredText = prismic.SharedSliceVariation<
  "centeredText",
  Simplify<ContentSliceCenteredTextPrimary>,
  never
>;

/**
 * Primary content in *Content → Image Right → Primary*
 */
export interface ContentSliceImageRightPrimary {
  /**
   * Eyebrow field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional short label above the heading
   * - **API ID Path**: content.imageRight.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: content.imageRight.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Editorial content
   * - **API ID Path**: content.imageRight.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Calls to action field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.imageRight.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<ContentSliceImageRightPrimaryCtasItem>>;

  /**
   * Section spacing field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose space above and below this section
   * - **Default Value**: standard
   * - **API ID Path**: content.imageRight.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the maximum content width
   * - **Default Value**: standard
   * - **API ID Path**: content.imageRight.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;

  /**
   * Image field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Right variation for Content Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<ContentSliceImageRightPrimary>,
  never
>;

/**
 * Primary content in *Content → Image Left → Primary*
 */
export interface ContentSliceImageLeftPrimary {
  /**
   * Eyebrow field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional short label above the heading
   * - **API ID Path**: content.imageLeft.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: content.imageLeft.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Editorial content
   * - **API ID Path**: content.imageLeft.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Calls to action field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.imageLeft.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<ContentSliceImageLeftPrimaryCtasItem>>;

  /**
   * Section spacing field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose space above and below this section
   * - **Default Value**: standard
   * - **API ID Path**: content.imageLeft.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the maximum content width
   * - **Default Value**: standard
   * - **API ID Path**: content.imageLeft.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;

  /**
   * Image field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.imageLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Left variation for Content Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<ContentSliceImageLeftPrimary>,
  never
>;

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation =
  | ContentSliceDefault
  | ContentSliceCenteredText
  | ContentSliceImageRight
  | ContentSliceImageLeft;

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSlice = prismic.SharedSlice<
  "content",
  ContentSliceVariation
>;

/**
 * Item in *Hero → Centered → Primary → Calls to action*
 */
export interface HeroSliceDefaultPrimaryCtasItem {
  /**
   * Label field in *Hero → Centered → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Hero → Centered → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Item in *Hero → Split → Primary → Calls to action*
 */
export interface HeroSliceSplitPrimaryCtasItem {
  /**
   * Label field in *Hero → Split → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.split.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Hero → Split → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.split.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Item in *Hero → Minimal → Primary → Calls to action*
 */
export interface HeroSliceMinimalPrimaryCtasItem {
  /**
   * Label field in *Hero → Minimal → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.minimal.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Hero → Minimal → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.minimal.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Primary content in *Hero → Centered → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Centered → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Eyebrow field in *Hero → Centered → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Body field in *Hero → Centered → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Hero → Centered → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Calls to action field in *Hero → Centered → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryCtasItem>>;

  /**
   * Section spacing field in *Hero → Centered → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: hero.default.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Hero → Centered → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: hero.default.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;
}

/**
 * Centered variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Split → Primary*
 */
export interface HeroSliceSplitPrimary {
  /**
   * Heading field in *Hero → Split → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.split.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Eyebrow field in *Hero → Split → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.split.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Body field in *Hero → Split → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.split.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Hero → Split → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.split.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Calls to action field in *Hero → Split → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.split.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<HeroSliceSplitPrimaryCtasItem>>;

  /**
   * Section spacing field in *Hero → Split → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: hero.split.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Hero → Split → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: hero.split.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;
}

/**
 * Split variation for Hero Slice
 *
 * - **API ID**: `split`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceSplit = prismic.SharedSliceVariation<
  "split",
  Simplify<HeroSliceSplitPrimary>,
  never
>;

/**
 * Primary content in *Hero → Minimal → Primary*
 */
export interface HeroSliceMinimalPrimary {
  /**
   * Heading field in *Hero → Minimal → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.minimal.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Eyebrow field in *Hero → Minimal → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.minimal.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Body field in *Hero → Minimal → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.minimal.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Calls to action field in *Hero → Minimal → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.minimal.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<HeroSliceMinimalPrimaryCtasItem>>;

  /**
   * Section spacing field in *Hero → Minimal → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: hero.minimal.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Hero → Minimal → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: hero.minimal.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;
}

/**
 * Minimal variation for Hero Slice
 *
 * - **API ID**: `minimal`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceMinimal = prismic.SharedSliceVariation<
  "minimal",
  Simplify<HeroSliceMinimalPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceSplit | HeroSliceMinimal;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Image → Full Width → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Full Width → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Section spacing field in *Image → Full Width → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: image.default.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Image → Full Width → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: image.default.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;
}

/**
 * Full Width variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Two Up → Primary*
 */
export interface ImageSliceTwoUpPrimary {
  /**
   * Image field in *Image → Two Up → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.twoUp.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Section spacing field in *Image → Two Up → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: image.twoUp.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Image → Two Up → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: image.twoUp.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;

  /**
   * Second image field in *Image → Two Up → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.twoUp.primary.second_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  second_image: prismic.ImageField<never>;
}

/**
 * Two Up variation for Image Slice
 *
 * - **API ID**: `twoUp`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceTwoUp = prismic.SharedSliceVariation<
  "twoUp",
  Simplify<ImageSliceTwoUpPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceTwoUp;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *Video → YouTube → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * YouTube video ID field in *Video → YouTube → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.youtube_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  youtube_id: prismic.KeyTextField;

  /**
   * Accessible title field in *Video → YouTube → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Section spacing field in *Video → YouTube → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.default.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Video → YouTube → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.default.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;
}

/**
 * YouTube variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Video → Uploaded Video → Primary*
 */
export interface VideoSliceUploadedVideoPrimary {
  /**
   * Accessible title field in *Video → Uploaded Video → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.uploadedVideo.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Section spacing field in *Video → Uploaded Video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.uploadedVideo.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Video → Uploaded Video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.uploadedVideo.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;

  /**
   * Video file field in *Video → Uploaded Video → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: video.uploadedVideo.primary.video_file
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_file: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Poster image field in *Video → Uploaded Video → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.uploadedVideo.primary.poster
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  poster: prismic.ImageField<never>;
}

/**
 * Uploaded Video variation for Video Slice
 *
 * - **API ID**: `uploadedVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceUploadedVideo = prismic.SharedSliceVariation<
  "uploadedVideo",
  Simplify<VideoSliceUploadedVideoPrimary>,
  never
>;

/**
 * Primary content in *Video → External Video → Primary*
 */
export interface VideoSliceExternalVideoPrimary {
  /**
   * Accessible title field in *Video → External Video → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.externalVideo.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Section spacing field in *Video → External Video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.externalVideo.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Video → External Video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.externalVideo.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;

  /**
   * Poster image field in *Video → External Video → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.externalVideo.primary.poster
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  poster: prismic.ImageField<never>;

  /**
   * Video URL field in *Video → External Video → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: video.externalVideo.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * External Video variation for Video Slice
 *
 * - **API ID**: `externalVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceExternalVideo = prismic.SharedSliceVariation<
  "externalVideo",
  Simplify<VideoSliceExternalVideoPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation =
  VideoSliceDefault | VideoSliceUploadedVideo | VideoSliceExternalVideo;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentSlice,
      ContentSliceDefaultPrimaryCtasItem,
      ContentSliceDefaultPrimary,
      ContentSliceCenteredTextPrimaryCtasItem,
      ContentSliceCenteredTextPrimary,
      ContentSliceImageRightPrimaryCtasItem,
      ContentSliceImageRightPrimary,
      ContentSliceImageLeftPrimaryCtasItem,
      ContentSliceImageLeftPrimary,
      ContentSliceVariation,
      ContentSliceDefault,
      ContentSliceCenteredText,
      ContentSliceImageRight,
      ContentSliceImageLeft,
      HeroSlice,
      HeroSliceDefaultPrimaryCtasItem,
      HeroSliceDefaultPrimary,
      HeroSliceSplitPrimaryCtasItem,
      HeroSliceSplitPrimary,
      HeroSliceMinimalPrimaryCtasItem,
      HeroSliceMinimalPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceSplit,
      HeroSliceMinimal,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceTwoUpPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceTwoUp,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceUploadedVideoPrimary,
      VideoSliceExternalVideoPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
      VideoSliceUploadedVideo,
      VideoSliceExternalVideo,
    };
  }
}
