// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice =
  | WhoIWorkWithSlice
  | InformationGridSlice
  | CallToActionSlice
  | HeadingAndTextSlice
  | ImageAndTextSlice
  | ContentSlice
  | ImageSlice
  | VideoSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | ConsultationFormSlice
  | LocationMapSlice
  | FaqAccordionSlice
  | AudienceAccordionSlice
  | InformationGridSlice
  | CallToActionSlice
  | HeadingAndTextSlice
  | ImageAndTextSlice
  | ContentSlice
  | VideoSlice
  | ImageSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Header navigation*
 */
export interface SettingsDocumentDataHeaderNavigationItem {
  /**
   * Label field in *Settings → Header navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Destination field in *Settings → Header navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Style as call to action field in *Settings → Header navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.header_navigation[].is_call_to_action
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_call_to_action: prismic.BooleanField;
}

type SettingsDocumentDataSlicesSlice = never;

/**
 * Item in *Settings → Footer navigation*
 */
export interface SettingsDocumentDataFooterNavigationItem {
  /**
   * Label field in *Settings → Footer navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Destination field in *Settings → Footer navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_name: prismic.KeyTextField;

  /**
   * Header navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  header_navigation: prismic.GroupField<
    Simplify<SettingsDocumentDataHeaderNavigationItem>
  >;

  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>; /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: settings.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: settings.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>; /**
   * Footer navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_navigation: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterNavigationItem>
  >;

  /**
   * Footer address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_address
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_address: prismic.KeyTextField;

  /**
   * Footer service details field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_service_details
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_service_details: prismic.KeyTextField;

  /**
   * Professional credential field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.professional_credential
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  professional_credential: prismic.KeyTextField;

  /**
   * Supervision statement field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.supervision_statement
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  supervision_statement: prismic.KeyTextField;

  /**
   * Emergency notice field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.emergency_notice
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  emergency_notice: prismic.KeyTextField;

  /**
   * Copyright notice field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright_notice
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_notice: prismic.KeyTextField;

  /**
   * Privacy link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.privacy_link
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  privacy_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >; /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: settings.meta_title_new
   * - **Tab**: SEO & Metadata New
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title_new: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: settings.meta_description_new
   * - **Tab**: SEO & Metadata New
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description_new: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image_new
   * - **Tab**: SEO & Metadata New
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image_new: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = HomeDocument | PageDocument | SettingsDocument;

/**
 * Item in *AudienceAccordion → Default → Primary → Audience items*
 */
export interface AudienceAccordionSliceDefaultPrimaryAudienceItemsItem {
  /**
   * Anchor ID field in *AudienceAccordion → Default → Primary → Audience items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_accordion.default.primary.audience_items[].anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * Audience name field in *AudienceAccordion → Default → Primary → Audience items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_accordion.default.primary.audience_items[].audience_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  audience_name: prismic.KeyTextField;

  /**
   * Summary field in *AudienceAccordion → Default → Primary → Audience items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_accordion.default.primary.audience_items[].summary
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  summary: prismic.KeyTextField;

  /**
   * Heading field in *AudienceAccordion → Default → Primary → Audience items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_accordion.default.primary.audience_items[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *AudienceAccordion → Default → Primary → Audience items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_accordion.default.primary.audience_items[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * CTA field in *AudienceAccordion → Default → Primary → Audience items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_accordion.default.primary.audience_items[].cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Image field in *AudienceAccordion → Default → Primary → Audience items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_accordion.default.primary.audience_items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *AudienceAccordion → Default → Primary*
 */
export interface AudienceAccordionSliceDefaultPrimary {
  /**
   * Audience items field in *AudienceAccordion → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: audience_accordion.default.primary.audience_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  audience_items: prismic.GroupField<
    Simplify<AudienceAccordionSliceDefaultPrimaryAudienceItemsItem>
  >;
}

/**
 * Default variation for AudienceAccordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AudienceAccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AudienceAccordionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AudienceAccordion*
 */
type AudienceAccordionSliceVariation = AudienceAccordionSliceDefault;

/**
 * AudienceAccordion Shared Slice
 *
 * - **API ID**: `audience_accordion`
 * - **Description**: AudienceAccordion
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AudienceAccordionSlice = prismic.SharedSlice<
  "audience_accordion",
  AudienceAccordionSliceVariation
>;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Heading field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Link field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Helper text field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.helper_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  helper_text: prismic.RichTextField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *ConsultationForm → Default → Primary*
 */
export interface ConsultationFormSliceDefaultPrimary {
  /**
   * About heading field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.about_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  about_heading: prismic.KeyTextField;

  /**
   * Session heading field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.session_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  session_heading: prismic.KeyTextField;

  /**
   * Before speaking heading field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.before_speak_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  before_speak_heading: prismic.KeyTextField;

  /**
   * Availability hint field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.availability_hint
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  availability_hint: prismic.KeyTextField;

  /**
   * Message hint field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.message_hint
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_hint: prismic.KeyTextField;

  /**
   * Consent text field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.consent_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  consent_text: prismic.KeyTextField;

  /**
   * Submit label field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.submit_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_label: prismic.KeyTextField;

  /**
   * Validation summary field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.validation_summary
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  validation_summary: prismic.KeyTextField;

  /**
   * Delivery unavailable message field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.delivery_unavailable_message
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  delivery_unavailable_message: prismic.KeyTextField;

  /**
   * Success heading field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.success_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  success_heading: prismic.KeyTextField;

  /**
   * Success message field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.success_message
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  success_message: prismic.KeyTextField;

  /**
   * Privacy link field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.privacy_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  privacy_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Success eyebrow field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.success_eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  success_eyebrow: prismic.KeyTextField;

  /**
   * Reset button label field in *ConsultationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_form.default.primary.reset_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  reset_label: prismic.KeyTextField;
}

/**
 * Default variation for ConsultationForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConsultationFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConsultationFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ConsultationForm*
 */
type ConsultationFormSliceVariation = ConsultationFormSliceDefault;

/**
 * ConsultationForm Shared Slice
 *
 * - **API ID**: `consultation_form`
 * - **Description**: ConsultationForm
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConsultationFormSlice = prismic.SharedSlice<
  "consultation_form",
  ConsultationFormSliceVariation
>;

/**
 * Item in *Content → Text Only → Primary → Calls to action*
 */
export interface ContentSliceDefaultPrimaryCtasItem {
  /**
   * Label field in *Content → Text Only → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button label
   * - **API ID Path**: content.default.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Content → Text Only → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional call to action
   * - **API ID Path**: content.default.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Item in *Content → Centered Text → Primary → Calls to action*
 */
export interface ContentSliceCenteredTextPrimaryCtasItem {
  /**
   * Label field in *Content → Centered Text → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button label
   * - **API ID Path**: content.centeredText.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Content → Centered Text → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional call to action
   * - **API ID Path**: content.centeredText.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Item in *Content → Image Right → Primary → Calls to action*
 */
export interface ContentSliceImageRightPrimaryCtasItem {
  /**
   * Label field in *Content → Image Right → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button label
   * - **API ID Path**: content.imageRight.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Content → Image Right → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional call to action
   * - **API ID Path**: content.imageRight.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Item in *Content → Image Left → Primary → Calls to action*
 */
export interface ContentSliceImageLeftPrimaryCtasItem {
  /**
   * Label field in *Content → Image Left → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button label
   * - **API ID Path**: content.imageLeft.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Content → Image Left → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional call to action
   * - **API ID Path**: content.imageLeft.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Primary content in *Content → Text Only → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * Eyebrow field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional short label above the heading
   * - **API ID Path**: content.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: content.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Editorial content
   * - **API ID Path**: content.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Calls to action field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<ContentSliceDefaultPrimaryCtasItem>>;

  /**
   * Section spacing field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose space above and below this section
   * - **Default Value**: standard
   * - **API ID Path**: content.default.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Content → Text Only → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the maximum content width
   * - **Default Value**: standard
   * - **API ID Path**: content.default.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;
}

/**
 * Text Only variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Content → Centered Text → Primary*
 */
export interface ContentSliceCenteredTextPrimary {
  /**
   * Eyebrow field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional short label above the heading
   * - **API ID Path**: content.centeredText.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: content.centeredText.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Editorial content
   * - **API ID Path**: content.centeredText.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Calls to action field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.centeredText.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<ContentSliceCenteredTextPrimaryCtasItem>>;

  /**
   * Section spacing field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose space above and below this section
   * - **Default Value**: standard
   * - **API ID Path**: content.centeredText.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Content → Centered Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the maximum content width
   * - **Default Value**: standard
   * - **API ID Path**: content.centeredText.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;
}

/**
 * Centered Text variation for Content Slice
 *
 * - **API ID**: `centeredText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceCenteredText = prismic.SharedSliceVariation<
  "centeredText",
  Simplify<ContentSliceCenteredTextPrimary>,
  never
>;

/**
 * Primary content in *Content → Image Right → Primary*
 */
export interface ContentSliceImageRightPrimary {
  /**
   * Eyebrow field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional short label above the heading
   * - **API ID Path**: content.imageRight.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: content.imageRight.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Editorial content
   * - **API ID Path**: content.imageRight.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Calls to action field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.imageRight.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<ContentSliceImageRightPrimaryCtasItem>>;

  /**
   * Section spacing field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose space above and below this section
   * - **Default Value**: standard
   * - **API ID Path**: content.imageRight.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the maximum content width
   * - **Default Value**: standard
   * - **API ID Path**: content.imageRight.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;

  /**
   * Image field in *Content → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Right variation for Content Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<ContentSliceImageRightPrimary>,
  never
>;

/**
 * Primary content in *Content → Image Left → Primary*
 */
export interface ContentSliceImageLeftPrimary {
  /**
   * Eyebrow field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional short label above the heading
   * - **API ID Path**: content.imageLeft.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: content.imageLeft.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Editorial content
   * - **API ID Path**: content.imageLeft.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Calls to action field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.imageLeft.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<ContentSliceImageLeftPrimaryCtasItem>>;

  /**
   * Section spacing field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose space above and below this section
   * - **Default Value**: standard
   * - **API ID Path**: content.imageLeft.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the maximum content width
   * - **Default Value**: standard
   * - **API ID Path**: content.imageLeft.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;

  /**
   * Image field in *Content → Image Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.imageLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Left variation for Content Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<ContentSliceImageLeftPrimary>,
  never
>;

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation =
  | ContentSliceDefault
  | ContentSliceCenteredText
  | ContentSliceImageRight
  | ContentSliceImageLeft;

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSlice = prismic.SharedSlice<
  "content",
  ContentSliceVariation
>;

/**
 * Item in *FaqAccordion → Default → Primary → FAQ Items*
 */
export interface FaqAccordionSliceDefaultPrimaryFaqItemsItem {
  /**
   * Question field in *FaqAccordion → Default → Primary → FAQ Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_accordion.default.primary.faq_items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FaqAccordion → Default → Primary → FAQ Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_accordion.default.primary.faq_items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *FaqAccordion → Default → Primary*
 */
export interface FaqAccordionSliceDefaultPrimary {
  /**
   * Heading field in *FaqAccordion → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_accordion.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * FAQ Items field in *FaqAccordion → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_accordion.default.primary.faq_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faq_items: prismic.GroupField<
    Simplify<FaqAccordionSliceDefaultPrimaryFaqItemsItem>
  >;
}

/**
 * Default variation for FaqAccordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqAccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqAccordionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqAccordion*
 */
type FaqAccordionSliceVariation = FaqAccordionSliceDefault;

/**
 * FaqAccordion Shared Slice
 *
 * - **API ID**: `faq_accordion`
 * - **Description**: FaqAccordion
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqAccordionSlice = prismic.SharedSlice<
  "faq_accordion",
  FaqAccordionSliceVariation
>;

/**
 * Primary content in *HeadingAndText → Side by Side → Primary*
 */
export interface HeadingAndTextSliceDefaultPrimary {
  /**
   * Heading field in *HeadingAndText → Side by Side → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *HeadingAndText → Side by Side → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Link field in *HeadingAndText → Side by Side → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Use wine background field in *HeadingAndText → Side by Side → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: heading_and_text.default.primary.use_wine_background
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  use_wine_background: prismic.BooleanField;
}

/**
 * Side by Side variation for HeadingAndText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadingAndTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadingAndTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeadingAndText → Two Columns → Primary*
 */
export interface HeadingAndTextSliceTwoColumnsPrimary {
  /**
   * Heading field in *HeadingAndText → Two Columns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.twoColumns.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Left body field in *HeadingAndText → Two Columns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.twoColumns.primary.left_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  left_body: prismic.RichTextField;

  /**
   * Right body field in *HeadingAndText → Two Columns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.twoColumns.primary.right_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  right_body: prismic.RichTextField;

  /**
   * Use wine background field in *HeadingAndText → Two Columns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: heading_and_text.twoColumns.primary.use_wine_background
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  use_wine_background: prismic.BooleanField;
}

/**
 * Two Columns variation for HeadingAndText Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadingAndTextSliceTwoColumns = prismic.SharedSliceVariation<
  "twoColumns",
  Simplify<HeadingAndTextSliceTwoColumnsPrimary>,
  never
>;

/**
 * Primary content in *HeadingAndText → Conversation Chapter → Primary*
 */
export interface HeadingAndTextSliceConversationChapterPrimary {
  /**
   * Heading field in *HeadingAndText → Conversation Chapter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.conversationChapter.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *HeadingAndText → Conversation Chapter → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.conversationChapter.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Use wine background field in *HeadingAndText → Conversation Chapter → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: heading_and_text.conversationChapter.primary.use_wine_background
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  use_wine_background: prismic.BooleanField;

  /**
   * Statement field in *HeadingAndText → Conversation Chapter → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A short pull-out statement
   * - **API ID Path**: heading_and_text.conversationChapter.primary.statement
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  statement: prismic.RichTextField;
}

/**
 * Conversation Chapter variation for HeadingAndText Slice
 *
 * - **API ID**: `conversationChapter`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadingAndTextSliceConversationChapter =
  prismic.SharedSliceVariation<
    "conversationChapter",
    Simplify<HeadingAndTextSliceConversationChapterPrimary>,
    never
  >;

/**
 * Slice variation for *HeadingAndText*
 */
type HeadingAndTextSliceVariation =
  | HeadingAndTextSliceDefault
  | HeadingAndTextSliceTwoColumns
  | HeadingAndTextSliceConversationChapter;

/**
 * HeadingAndText Shared Slice
 *
 * - **API ID**: `heading_and_text`
 * - **Description**: HeadingAndText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadingAndTextSlice = prismic.SharedSlice<
  "heading_and_text",
  HeadingAndTextSliceVariation
>;

/**
 * Item in *Hero → Homepage Hero → Primary → Calls to action*
 */
export interface HeroSliceDefaultPrimaryCtasItem {
  /**
   * Label field in *Hero → Homepage Hero → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Hero → Homepage Hero → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Item in *Hero → Full Image Homepage Hero → Primary → Calls to action*
 */
export interface HeroSliceFullImagePrimaryCtasItem {
  /**
   * Label field in *Hero → Full Image Homepage Hero → Primary → Calls to action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.fullImage.primary.ctas[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Hero → Full Image Homepage Hero → Primary → Calls to action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.fullImage.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Outline"
  >;
}

/**
 * Primary content in *Hero → Homepage Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Homepage Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Lead field in *Hero → Homepage Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.lead
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  lead: prismic.RichTextField;

  /**
   * Animation poster field in *Hero → Homepage Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.animation_poster
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  animation_poster: prismic.ImageField<never>;

  /**
   * Calls to action field in *Hero → Homepage Hero → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryCtasItem>>;

  /**
   * Supporting copy field in *Hero → Homepage Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.supporting_copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  supporting_copy: prismic.RichTextField;

  /**
   * Helper copy field in *Hero → Homepage Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.helper_copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  helper_copy: prismic.RichTextField;
}

/**
 * Homepage Hero variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Inner Page Hero → Primary*
 */
export interface HeroSliceSplitPrimary {
  /**
   * Heading field in *Hero → Inner Page Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.split.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Lead field in *Hero → Inner Page Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.split.primary.lead
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  lead: prismic.RichTextField;

  /**
   * Image field in *Hero → Inner Page Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.split.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Supporting copy field in *Hero → Inner Page Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.split.primary.supporting_copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  supporting_copy: prismic.RichTextField;
}

/**
 * Inner Page Hero variation for Hero Slice
 *
 * - **API ID**: `split`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceSplit = prismic.SharedSliceVariation<
  "split",
  Simplify<HeroSliceSplitPrimary>,
  never
>;

/**
 * Primary content in *Hero → Full Image Homepage Hero → Primary*
 */
export interface HeroSliceFullImagePrimary {
  /**
   * Heading field in *Hero → Full Image Homepage Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.fullImage.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Lead field in *Hero → Full Image Homepage Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.fullImage.primary.lead
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  lead: prismic.RichTextField;

  /**
   * Background image field in *Hero → Full Image Homepage Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.fullImage.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Calls to action field in *Hero → Full Image Homepage Hero → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.fullImage.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  ctas: prismic.GroupField<Simplify<HeroSliceFullImagePrimaryCtasItem>>;

  /**
   * Supporting copy field in *Hero → Full Image Homepage Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.fullImage.primary.supporting_copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  supporting_copy: prismic.RichTextField;

  /**
   * Helper copy field in *Hero → Full Image Homepage Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.fullImage.primary.helper_copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  helper_copy: prismic.RichTextField;
}

/**
 * Full Image Homepage Hero variation for Hero Slice
 *
 * - **API ID**: `fullImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceFullImage = prismic.SharedSliceVariation<
  "fullImage",
  Simplify<HeroSliceFullImagePrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  HeroSliceDefault | HeroSliceSplit | HeroSliceFullImage;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Image → Full Width → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Full Width → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Section spacing field in *Image → Full Width → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: image.default.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Image → Full Width → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: image.default.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;
}

/**
 * Full Width variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Two Up → Primary*
 */
export interface ImageSliceTwoUpPrimary {
  /**
   * Image field in *Image → Two Up → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.twoUp.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Section spacing field in *Image → Two Up → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: image.twoUp.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Image → Two Up → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: image.twoUp.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;

  /**
   * Second image field in *Image → Two Up → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.twoUp.primary.second_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  second_image: prismic.ImageField<never>;
}

/**
 * Two Up variation for Image Slice
 *
 * - **API ID**: `twoUp`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceTwoUp = prismic.SharedSliceVariation<
  "twoUp",
  Simplify<ImageSliceTwoUpPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceTwoUp;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *ImageAndText → Default → Primary*
 */
export interface ImageAndTextSliceDefaultPrimary {
  /**
   * Image field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Link field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Supporting heading field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.supporting_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  supporting_heading: prismic.KeyTextField;

  /**
   * Supporting body field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.supporting_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  supporting_body: prismic.RichTextField;

  /**
   * Add background color field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_and_text.default.primary.add_background_color
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  add_background_color: prismic.BooleanField;

  /**
   * Add top border field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_and_text.default.primary.add_top_border
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  add_top_border: prismic.BooleanField;

  /**
   * Add bottom border field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_and_text.default.primary.add_bottom_border
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  add_bottom_border: prismic.BooleanField;
}

/**
 * Default variation for ImageAndText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageAndTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageAndTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageAndText*
 */
type ImageAndTextSliceVariation = ImageAndTextSliceDefault;

/**
 * ImageAndText Shared Slice
 *
 * - **API ID**: `image_and_text`
 * - **Description**: ImageAndText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageAndTextSlice = prismic.SharedSlice<
  "image_and_text",
  ImageAndTextSliceVariation
>;

/**
 * Item in *InformationGrid → Default → Primary → Items*
 */
export interface InformationGridSliceDefaultPrimaryItemsItem {
  /**
   * Heading field in *InformationGrid → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_grid.default.primary.items[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *InformationGrid → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_grid.default.primary.items[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *InformationGrid → Default → Primary*
 */
export interface InformationGridSliceDefaultPrimary {
  /**
   * Heading field in *InformationGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Items field in *InformationGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: information_grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<InformationGridSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for InformationGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InformationGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InformationGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InformationGrid*
 */
type InformationGridSliceVariation = InformationGridSliceDefault;

/**
 * InformationGrid Shared Slice
 *
 * - **API ID**: `information_grid`
 * - **Description**: InformationGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InformationGridSlice = prismic.SharedSlice<
  "information_grid",
  InformationGridSliceVariation
>;

/**
 * Primary content in *LocationMap → Default → Primary*
 */
export interface LocationMapSliceDefaultPrimary {
  /**
   * Heading field in *LocationMap → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_map.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *LocationMap → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_map.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Address field in *LocationMap → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_map.default.primary.address
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Map Link field in *LocationMap → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: location_map.default.primary.map_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  map_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for LocationMap Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationMapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LocationMapSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LocationMap*
 */
type LocationMapSliceVariation = LocationMapSliceDefault;

/**
 * LocationMap Shared Slice
 *
 * - **API ID**: `location_map`
 * - **Description**: LocationMap
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationMapSlice = prismic.SharedSlice<
  "location_map",
  LocationMapSliceVariation
>;

/**
 * Primary content in *Video → YouTube → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * YouTube video ID field in *Video → YouTube → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.youtube_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  youtube_id: prismic.KeyTextField;

  /**
   * Accessible title field in *Video → YouTube → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Section spacing field in *Video → YouTube → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.default.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Video → YouTube → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.default.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;
}

/**
 * YouTube variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Video → Uploaded Video → Primary*
 */
export interface VideoSliceUploadedVideoPrimary {
  /**
   * Accessible title field in *Video → Uploaded Video → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.uploadedVideo.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Section spacing field in *Video → Uploaded Video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.uploadedVideo.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Video → Uploaded Video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.uploadedVideo.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;

  /**
   * Video file field in *Video → Uploaded Video → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: video.uploadedVideo.primary.video_file
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_file: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Poster image field in *Video → Uploaded Video → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.uploadedVideo.primary.poster
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  poster: prismic.ImageField<never>;
}

/**
 * Uploaded Video variation for Video Slice
 *
 * - **API ID**: `uploadedVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceUploadedVideo = prismic.SharedSliceVariation<
  "uploadedVideo",
  Simplify<VideoSliceUploadedVideoPrimary>,
  never
>;

/**
 * Primary content in *Video → External Video → Primary*
 */
export interface VideoSliceExternalVideoPrimary {
  /**
   * Accessible title field in *Video → External Video → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.externalVideo.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Section spacing field in *Video → External Video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.externalVideo.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "standard" | "compact" | "none" | "none-above" | "none-below",
    "filled"
  >;

  /**
   * Content width field in *Video → External Video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: video.externalVideo.primary.width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  width: prismic.SelectField<"standard" | "narrow" | "full", "filled">;

  /**
   * Poster image field in *Video → External Video → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.externalVideo.primary.poster
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  poster: prismic.ImageField<never>;

  /**
   * Video URL field in *Video → External Video → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: video.externalVideo.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * External Video variation for Video Slice
 *
 * - **API ID**: `externalVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceExternalVideo = prismic.SharedSliceVariation<
  "externalVideo",
  Simplify<VideoSliceExternalVideoPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation =
  VideoSliceDefault | VideoSliceUploadedVideo | VideoSliceExternalVideo;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

/**
 * Item in *WhoIWorkWith → Default → Primary → Audience items*
 */
export interface WhoIWorkWithSliceDefaultPrimaryAudienceItemsItem {
  /**
   * Audience name field in *WhoIWorkWith → Default → Primary → Audience items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_i_work_with.default.primary.audience_items[].audience_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  audience_name: prismic.KeyTextField;

  /**
   * Audience image field in *WhoIWorkWith → Default → Primary → Audience items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: who_i_work_with.default.primary.audience_items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *WhoIWorkWith → Default → Primary → Audience items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_i_work_with.default.primary.audience_items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Audience link field in *WhoIWorkWith → Default → Primary → Audience items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: who_i_work_with.default.primary.audience_items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *WhoIWorkWith → Default → Primary*
 */
export interface WhoIWorkWithSliceDefaultPrimary {
  /**
   * Heading field in *WhoIWorkWith → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_i_work_with.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Practice note field in *WhoIWorkWith → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_i_work_with.default.primary.practice_note
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  practice_note: prismic.RichTextField;

  /**
   * Audience items field in *WhoIWorkWith → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: who_i_work_with.default.primary.audience_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  audience_items: prismic.GroupField<
    Simplify<WhoIWorkWithSliceDefaultPrimaryAudienceItemsItem>
  >;
}

/**
 * Default variation for WhoIWorkWith Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhoIWorkWithSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhoIWorkWithSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhoIWorkWith*
 */
type WhoIWorkWithSliceVariation = WhoIWorkWithSliceDefault;

/**
 * WhoIWorkWith Shared Slice
 *
 * - **API ID**: `who_i_work_with`
 * - **Description**: WhoIWorkWith
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhoIWorkWithSlice = prismic.SharedSlice<
  "who_i_work_with",
  WhoIWorkWithSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataHeaderNavigationItem,
      SettingsDocumentDataSlicesSlice,
      SettingsDocumentDataFooterNavigationItem,
      AllDocumentTypes,
      AudienceAccordionSlice,
      AudienceAccordionSliceDefaultPrimaryAudienceItemsItem,
      AudienceAccordionSliceDefaultPrimary,
      AudienceAccordionSliceVariation,
      AudienceAccordionSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      ConsultationFormSlice,
      ConsultationFormSliceDefaultPrimary,
      ConsultationFormSliceVariation,
      ConsultationFormSliceDefault,
      ContentSlice,
      ContentSliceDefaultPrimaryCtasItem,
      ContentSliceDefaultPrimary,
      ContentSliceCenteredTextPrimaryCtasItem,
      ContentSliceCenteredTextPrimary,
      ContentSliceImageRightPrimaryCtasItem,
      ContentSliceImageRightPrimary,
      ContentSliceImageLeftPrimaryCtasItem,
      ContentSliceImageLeftPrimary,
      ContentSliceVariation,
      ContentSliceDefault,
      ContentSliceCenteredText,
      ContentSliceImageRight,
      ContentSliceImageLeft,
      FaqAccordionSlice,
      FaqAccordionSliceDefaultPrimaryFaqItemsItem,
      FaqAccordionSliceDefaultPrimary,
      FaqAccordionSliceVariation,
      FaqAccordionSliceDefault,
      HeadingAndTextSlice,
      HeadingAndTextSliceDefaultPrimary,
      HeadingAndTextSliceTwoColumnsPrimary,
      HeadingAndTextSliceConversationChapterPrimary,
      HeadingAndTextSliceVariation,
      HeadingAndTextSliceDefault,
      HeadingAndTextSliceTwoColumns,
      HeadingAndTextSliceConversationChapter,
      HeroSlice,
      HeroSliceDefaultPrimaryCtasItem,
      HeroSliceDefaultPrimary,
      HeroSliceSplitPrimary,
      HeroSliceFullImagePrimaryCtasItem,
      HeroSliceFullImagePrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceSplit,
      HeroSliceFullImage,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceTwoUpPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceTwoUp,
      ImageAndTextSlice,
      ImageAndTextSliceDefaultPrimary,
      ImageAndTextSliceVariation,
      ImageAndTextSliceDefault,
      InformationGridSlice,
      InformationGridSliceDefaultPrimaryItemsItem,
      InformationGridSliceDefaultPrimary,
      InformationGridSliceVariation,
      InformationGridSliceDefault,
      LocationMapSlice,
      LocationMapSliceDefaultPrimary,
      LocationMapSliceVariation,
      LocationMapSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceUploadedVideoPrimary,
      VideoSliceExternalVideoPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
      VideoSliceUploadedVideo,
      VideoSliceExternalVideo,
      WhoIWorkWithSlice,
      WhoIWorkWithSliceDefaultPrimaryAudienceItemsItem,
      WhoIWorkWithSliceDefaultPrimary,
      WhoIWorkWithSliceVariation,
      WhoIWorkWithSliceDefault,
    };
  }
}
